apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: iiot_timescaledb
    access: proxy
    url: timescaledb:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASS}
    database: ${DB_NAME}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: true
      database: iiot_db
    isDefault: true
    editable: true
