apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: iiot_timescaledb
    access: proxy
    url: timescaledb:5432
    user: iiot_user
    secureJsonData:
      password: iiot_password
    database: iiot_db
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: true
      database: iiot_db
    isDefault: true
    editable: true
